---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: agent-sandbox-controller
  namespace: agent-sandbox-system
  labels:
    app: agent-sandbox-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-sandbox-controller
  template:
    metadata:
      labels:
        app: agent-sandbox-controller
    spec:
      serviceAccountName: agent-sandbox-controller
      containers:
      - name: agent-sandbox-controller
        image: ko://sigs.k8s.io/agent-sandbox/cmd/agent-sandbox-controller # placeholder value, replaced by deployment scripts
        imagePullPolicy: Always
        args:
        - "--leader-elect=true"
        - "--extensions"
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        - name: healthz
          containerPort: 8081
          protocol: TCP
      # - name: metrics-proxy
      #   image: us-central1-docker.pkg.dev/gke-ai-open-models/agent-sandbox-repo/prometheus-metric-proxy:v20260320-v0.2.1-15-ga2d311d-dirty@sha256:a2b81de81473246d0848be02e1ee571eca6641198ca5c6e57e0a74900abcc334
      #   imagePullPolicy: IfNotPresent
      #   command: ["/k8s-http-proxy"]
      #   ports:
      #   - name: metrics-proxy
      #     containerPort: 9091
      #     protocol: TCP
      #   args:
      #   - "--port=9091"
      #   - "--proxy-path=/"
      #   - "--target-url=http://localhost:8080"
