apiVersion: autoscaling.x-k8s.io/v1beta1
kind: CapacityBuffer
metadata:
  name: agent-warmpool-buffer
  namespace: sandbox-test
spec:
  # Maintain a node buffer equal to 200% of the SandboxWarmPool's replicas
  percentage: 200
  scalableRef:
    apiGroup: extensions.agents.x-k8s.io
    kind: SandboxWarmPool
    name: python-sdk-warmpool

  # The strategy for provisioning. 
  # cold-capacity creates suspended VMs that resume in ~30s.
  # active-capacity triggers immediate scale-up.
  provisioningStrategy: "buffer.gke.io/cold-capacity"