apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agent-warmpool-hpa
  namespace: sandbox-test
spec:
  scaleTargetRef:
    apiVersion: extensions.agents.x-k8s.io/v1alpha1
    kind: SandboxWarmPool
    name: python-sdk-warmpool
  minReplicas: 10
  maxReplicas: 50
  metrics:
    - type: Pods
      pods:
        metric:
          name: autoscaling.gke.io|agent-active-claim-rate|agent_sandbox_claim_per_minute # Matches the metric name exposed by AutoscalingMetric
        target:
          type: AverageValue
          averageValue: 20
    # - type: Object
    #   object:
    #     metric:
    #       # Matches the name given in the AutoscalingMetric CRD
    #       name: autoscaling.gke.io|agent-active-claim-rate|agent_sandbox_claim_per_minute
    #     describedObject:
    #       apiVersion: v1
    #       kind: Service
    #       name: agent-sandbox-controller
    #     target:
    #       type: Value 
    #       value: "5"
    # - type: External
    #   external:
    #     metric:
    #       name: autoscaling.gke.io|agent-active-claim-rate|agent_sandbox_claim_per_minute
    #     target:
    #       type: Value 
    #       value: "5"

 # factor - how longs it takes to add to the worker pool 

# oscillating 
# utilization of sandbox 
# some pressure of the sandboxwarmpool ? 
# 
