apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxTemplate
metadata:
  name: python-counter-template
  namespace: sandbox-test
  labels:
    language: python
spec:
  #enableDisruptionControl: true
  #shutdownTime: "2025-12-31T23:59:59Z"
  podTemplate:
    metadata:
      labels:
        app: agent-sandbox-workload
        tenant-id: "test-tenant"
        user-id: "test-user"
    spec:
      serviceAccountName: sandbox-test
      # automountServiceAccountToken: true
      # dnsPolicy: ClusterFirst
      # runtimeClassName: gvisor
      containers:
      - name: my-container1
        image: python:3.10-slim
        command: ["python3", "-c"]
        args:
          - |
            import time
            i = 0
            while True:
              print(f"Count: {i}", flush=True)
              i += 1
              time.sleep(1)
      # - name: metrics-proxy
      #   image: us-central1-docker.pkg.dev/shrutiyam-gke-dev/agent-sandbox-repo/prometheus-metric-proxy:v20260405-v0.2.1-36-g6ad4524-dirty
      #   command: ["/k8s-http-proxy"]
      #   ports:
      #   - name: metrics-proxy
      #     containerPort: 9091
      #     protocol: TCP
      #   args:
      #   - "--port=9091"
      #   - "--proxy-path=/"
      #   - "--target-url=http://agent-sandbox-controller.agent-sandbox-system.svc.cluster.local:8080/"
      #   - "--override-auth=false"